name: nndl_project
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=2.117
  - blas-devel=3.9.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=41.0.2
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.2.2
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=68.1
  - idna=3.4
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.23.4
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.3.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm12=12.0.0
  - libopenblas=0.3.23
  - libopus=1.3
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lxml=4.9.2
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - openblas=0.3.23
  - openh264=1.8.0
  - openssl=1.1.1v
  - packaging=23.0
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=21.2.4
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - pytz=2022.7
  - pyzmq=22.3.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.1.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=5.1.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2022a
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=4.0.5
  - x264=1!152.20180806
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alibi-detect==0.11.4
      - async-timeout==4.0.3
      - audioread==3.0.0
      - cachetools==5.3.1
      - captum==0.6.0
      - catalogue==2.0.9
      - cloudpickle==2.2.1
      - dill==0.3.7
      - frozenlist==1.4.0
      - fsspec==2023.9.1
      - google-auth==2.23.0
      - huggingface-hub==0.17.2
      - imageio==2.31.3
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.40.1
      - mdurl==0.1.2
      - msgpack==1.0.5
      - multidict==6.0.4
      - numba==0.57.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - opencv-python==4.8.0.76
      - patsy==0.5.3
      - platformdirs==3.10.0
      - pooch==1.7.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.12
      - pygments==2.16.1
      - pyqt5-sip==12.11.0
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rsa==4.9
      - safetensors==0.3.3
      - scikit-image==0.21.0
      - seaborn==0.12.2
      - shap==0.42.1
      - slicer==0.0.7
      - soundfile==0.12.1
      - soxr==0.3.6
      - statsmodels==0.14.0
      - tensorboard-data-server==0.7.1
      - tifffile==2023.9.18
      - tokenizers==0.13.3
      - torch==1.13.1
      - torchmetrics==0.11.4
      - torchsummary==1.5.1
      - transformers==4.33.2
      - werkzeug==2.3.7
      - yarl==1.9.2
